#define BLUETOOTH_DEVICE_NAME "KnobKoKy"
#define BLUETOOTH_DEVICE_MANUFACTURER "KoKy"
#define BLUETOOTH_DEVICE_BATTERY_LEVEL_DEFAULT 100

#define KNOB_BUTTON_SHORT_PRESS_MS 50
#define KNOB_BUTTON_LONG_PRESS_MS 1000
